# Default colors
[colors.primary]
background = "#1A1B26"
foreground = "#C0CAF5"

# Cursor colors
[colors.cursor]
cursor = "#C0CAF5"
text = "#1A1B26"

# Normal colors
[colors.normal]
black = "#15161E"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#A9B1D6"

# Bright colors
[colors.bright]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"
